copyright: Copyright © 2024-2024 the <a href="https://dimitrysaf.github.io/el.ltsp.org/">Υποστήριξη LTSP</a>
dev_addr: 0.0.0.0:7101
edit_uri: tree/main/docs
docs_dir: docs/
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: Περιεχόμενα Σελίδας
plugins:
  - minify:
      minify_html: false
  - search
  - with-pdf:
      author: Έκδοση pdf του Dimitrys_AF
      copyright: Copyright © 2024-2024 Υποστήριξη LTSP
      cover_title: Εγχειρίδιο για τα Linux
      cover_subtitle: LMDE 6/LTSP/Epoptes/sch-scripts
      debug_html: false
      enabled_if_env: ENABLE_PDF_EXPORT
      heading_shift: true
      ordered_chapter_level: 2
      output_path: linux_man.pdf
      toc_level: 2
      toc_title: Πίνακας Περιεχομένων
repo_url: https://github.com/Dimitrysaf/el.ltsp.org
site_name: Υποστήριξη LTSP
site_url: https://dimitrysaf.github.io/el.ltsp.org
strict: false
theme:
  # favicon: favicon.ico
  features:
    - todo-navigation.instant
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
  language: el
  locale: el
  logo: stylesheets/ts-logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Αλλαγή σε Σκούρο Θέμα
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Αλλαγή σε Ανοιχτό Θέμα
  titles_only: true
nav:
  - index.md